#!/usr/bin/env bash

source "$(dirname "$0")"/../.util/run.sh
source "$(dirname "$0")"/../.util/io.sh

[ -z "$DOTFILES_PATH" ] && fatal 'variable DOTFILES_PATH needs to be set!'

# Copy config into ~/.config
run cp -r "$DOTFILES_PATH"/.config/tmux ~/.config/tmux
