#!/usr/bin/env bash

source ../.util/install.sh
source ../.util/run.sh

install_pacman tmux
install_dnf tmux

run rm -rf "$HOME/repo/tmux-sessionizer"
run git clone https://github.com/ThePrimeagen/tmux-sessionizer.git "$HOME/repo/tmux-sessionizer"
run cp "$HOME/repo/tmux-sessionizer/tmux-sessionizer" "$HOME/.local/bin/"

./config
