FROM archlinux:latest

ARG USER=mcx

RUN pacman -Sy --noconfirm sudo archlinux-keyring

RUN useradd -m ${USER} && mkdir /home/${USER}/.dotfiles &&\
	usermod -aG wheel ${USER} &&\
	sed -Ei '/^# %wheel\s+ALL.*NOPASSWD: ALL$/ s/# //' /etc/sudoers

WORKDIR /home/mcx/.dotfiles


USER ${USER}

COPY . .

CMD [ "sh", "-c", "/home/mcx/.dotfiles/setup.sh --no-dry ; bash" ]

