FROM fedora:latest

ARG USER=mcx

RUN dnf install -y util-linux && dnf clean all

RUN useradd -m ${USER} && mkdir /home/${USER}/.dotfiles &&\
	usermod -aG wheel ${USER} &&\
	sed -Ei '/^# %wheel\s+ALL.*NOPASSWD: ALL$/ s/# //' /etc/sudoers

WORKDIR /home/mcx/.dotfiles

USER ${USER}

RUN echo 'source ./setup.sh -n' >> ~/.bash_history && \
    echo './setup.sh -yns bash' >> ~/.bash_history

COPY . .

CMD [ "sh", "-c", "/home/mcx/.dotfiles/setup.sh -n ; bash" ]

