FROM archlinux:latest

ARG USER=mcx

RUN pacman -Sy --noconfirm sudo archlinux-keyring

RUN useradd -m ${USER} && mkdir /home/${USER}/.dotfiles &&\
    usermod -aG wheel ${USER} &&\
    sed -i '/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/ s/# //' /etc/sudoers

WORKDIR /home/mcx/.dotfiles

COPY . .

USER mcx

CMD [ "sh", "-c", "/home/mcx/.dotfiles/setup.sh --no-dry ; bash" ]

