#!/usr/bin/env bash

source "$(dirname "$0")"/../../.util/run.sh

install_pacman zsh
install_dnf zsh

#TODO install zinit plugin manager and add stuff to .zshrc
#TODO move zsh files into XDG_ directories
