#!/usr/bin/env bash

source ../.util/io.sh
source ../.util/run.sh

[ -z "$DOTFILES_PATH" ] && fatal 'variable DOTFILES_PATH needs to be set!'

# Merge config
run cp --backup --recursive "$DOTFILES_PATH"/.config/nvim/* ~/.config/nvim/
run cp --backup --recursive "$DOTFILES_PATH"/.config/nvim/.* ~/.config/nvim/
