#!/usr/bin/env bash

source "$(dirname "$0")"/../.util/io.sh
source "$(dirname "$0")"/../.util/run.sh

[ -z "$DOTFILES_PATH" ] && fatal 'variable DOTFILES_PATH needs to be set!'

# Merge config
run cp -r "$DOTFILES_PATH"/.config/nvim/* ~/.config/nvim/
run cp -r "$DOTFILES_PATH"/.config/nvim/.* ~/.config/nvim/
