#!/usr/bin/env bash

source "$(dirname "$0")"/../.util/run.sh
source "$(dirname "$0")"/../.util/install.sh

install_pacman neovim
install_dnf neovim

run ln -s "$(which nvim)" "$HOME/.local/bin/vim"

# Install lazyvim (distro)
run mv ~/.config/nvim{,.bak}
run git clone https://github.com/LazyVim/starter ~/.config/nvim
run rm -rf ~/.config/nvim/.git

./config
