#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed neovim
sudo dnf install -y neovim

ln -s "$(which nvim)" "$HOME/.local/bin/vim"

# Install lazyvim (distro)
mv ~/.config/nvim{,.bak}
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

./config
