#!/usr/bin/env bash

# Use this file to run commands that are used to update copied config files
# so you don't have to reinstall just to update the config, thus you don't need this
# file if you just symlink the whole config folder to ~/.config

# source "$(dirname "$0")"/../.util/run.sh
# source "$(dirname "$0")"/../.util/io.sh

[ -z "$DOTFILES_PATH" ] && fatal 'variable DOTFILES_PATH needs to be set!'

# Copy config into ~/.config
# run cp -r "$DOTFILES_PATH"/.config/PROGRAM ~/.config/PROGRAM
