#!/usr/bin/env bash

source "$(dirname "$0")"/../.util/run.sh

REPO_PATH=""

[ -d "$REPO_PATH" ] && run rm -rf "$REPO_PATH"
run git clone https://github.com/ErrorNoInternet/asmfetch "$REPO_PATH"

DISTRO_NAME="$(sed -n '/^ID=/ s/ID=//p' /etc/os-release)"

# Build and Install
pushd "$REPO_PATH" || exit 1
run sed -iE 's|(\.include "logo/).*(\.S")|\1'"$DISTRO_NAME"'\2|' asmfetch.S

run gcc -nostdlib -no-pie asmfetch.S -o asmfetch
run cp asmfetch "$HOME/.local/bin/"
popd || exit 1
