#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    # newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    template = '{{.Icon}} '
    background = 'transparent'
    foreground = 'p:os'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ .UserName }}@{{ .HostName }} '
    background = 'transparent'
    foreground = 'p:blue'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    background = 'transparent'
    foreground = 'p:pink'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '{{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed)}}*{{end}} {{if gt .Behind 0}}⇣{{end}}{{if gt .Ahead 0}}⇣{{end}}'
    background = 'transparent'
    foreground = 'p:lavender'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
        branch_icon = ' '
        cherry_pick_icon = ' '
        commit_icon = ' '
        fetch_status = true
        fetch_upstream_icon = false
        merge_icon = ' '
        no_commits_icon = ' '
        rebase_icon = ' '
        revert_icon = ' '
        tag_icon = ' '

[[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

    [[blocks.segments]]
        type = 'executiontime'
        style = 'plain'
        foreground = 'p:peach'
        background = 'transparent'
        template = '{{ .FormattedMs }}'

        [blocks.segments.properties]
            threshold = 500

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        template = '$'
        background = 'transparent'
        foreground_templates = [
            '{{if gt .Code 0}}red{{end}}',
            '{{if eq .Code 0}}p:closer{{end}}'
        ]
        Text = ''
        Duration = 0
        NameLength = 0

[transient_prompt]
    template = '$ '
    background = 'transparent'
    foreground = 'p:closer'
    foreground_templates = [
        '{{if gt .Code 0}}red{{end}}',
        '{{if eq .Code 0}}p:closer{{end}}'
    ]

[secondary_prompt]
    foreground = 'p:closer2'
    background = 'transparent'
    template = '$❭ '

[palette]
    blue = '#89B4FA'
    closer = 'p:os'
    lavender = '#B4BEFE'
    os = '#9399b2'
    pink = '#F5C2E7'
    sky = '#89dceb'
    peach = '#fab387'
    closer2 = '#7f849c'

