#!/usr/bin/env bash

REPO_PATH=""

[ -d "$REPO_PATH" ] && rm -rf "$REPO_PATH"
git clone https://github.com/ErrorNoInternet/asmfetch "$REPO_PATH"

# Build and Install
pushd "$REPO_PATH" || exit 1
gcc -nostdlib -no-pie asmfetch.S -o asmfetch
cp asmfetch "$HOME/.local/bin/"
popd || exit 1
