####################
## Layout Actions ##
####################

# dwindle
bindd = $mainMod, P, Toggle Pseudotile, pseudo,
bindd = $mainMod, J, Toggle split direction, layoutmsg, togglesplit
bindd = $mainMod, K, Toggle split direction, layoutmsg, swapsplit

